### ISSUE TITLE
Image Issue

### ISSUE THREAD

**Issue by jessa-clark** [geraldfingburke/plateau-tarot-api#2]
Hello! I am using the API you built for a class project (my first one!) I'm making a very basic tarot app. I noticed an error in the API for "The Wheel of Fortune" card. The imageURL pulled from the API gives me a 404. The image link attached to that index is ```https://indiealchemy.com/apis/plateautarot/images/The%20Wheel%20of%20Fortune.jpg``` which returns a 404. I noticed in your image folder the image link you have for "The Wheel of Fortune" is ```https://indiealchemy.com/apis/plateautarot/images/Wheel%20of%20Fortune.jpg``` which is different from the link attached to the API. Would it be possible for you to change the link in the API so I can use it for my project? I really appreciate you and all the work you have put into this!!!

**Comment by geraldfingburke** [comment]
Sorry, didn't see this til now. It should be good to go now. Thank you for bringing it to my attention!
