### ISSUE TITLE
Reversed Cards

### ISSUE THREAD

**Issue by TiltdImage** [geraldfingburke/plateau-tarot-api#4]
Hello! Found your link on Luciella Scarletts page and firstly wanted thank you so much for putting this into an api for apps! You both are amazing human beings! 

I'm not really a coder but can read some code, so I am not sure if this is already a function... I was wondering when dealing the deck of cards if it is possible for the deal to have the cards able to be reversed (upside down) as that would impact the reading and make it more accurate. 

Before finding this page I was planning on just duplicating the deck and making the cards reversed and adding them into the random shuffle. However, thr problem with that is you could potentially pull the regular and reversed version of the same card, leading to the world imploding into a singularity! Lol

Is there a way for this API to have the ability to pull the reversed version of the card in the shuffle?

Thank you again!!

**Comment by geraldfingburke** [comment]
I've added the card backs to the card data. Let me know if this is what you were thinking, otherwise, you can reopen the issue.
